name: Auto PR Bot

on:
  pull_request_target:
    types: [edited, opened, reopened, synchronize]
  pull_request:
    types: [ready_for_review]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Google Gemini SDK
        run: pip install google-generativeai

      - name: List available models
        id: list_models
        run: |
          python .github/agent/list_models.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        shell: bash

      - name: Run the Agent model
        if: steps.list_models.outputs.model != ''
        run: |
          echo "Running the agent with model: ${{ steps.list_models.outputs.model }}"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          GITHUB_REPO: ${{ github.repository }}
        shell: bash
